# Generated by Django 3.0.3 on 2020-03-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200303_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='default@email.com', max_length=64, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
